package commom

type RouterGroup struct {
	// Code generated by github.com/88act/go-cms/server Begin; DO NOT EDIT.
	CommonDbRouter
	CommonFileRouter
	// Code generated by github.com/88act/go-cms/server End; DO NOT EDIT.
}
