// Code generated by goctl. DO NOT EDIT.
package types

type ArtDetailResp struct {
	Id         int64  `json:"id"`         //  id
	UserId     int64  `json:"userId"`     //用户id
	Type       int    `json:"type"`       //文章类型
	Title      string `json:"title"`      //文章标题
	Desc       string `json:"desc"`       //文章摘要
	TagList    string `json:"tagList"`    //标签列表
	Source     string `json:"source"`     //来源
	Image      string `json:"image"`      //插图
	Link       string `json:"link"`       //链接地址
	TotalWhole int    `json:"totalWhole"` //综合指数
	TotalShare int    `json:"totalShare"` //总分享
	TotalClick int    `json:"totalClick"` //总点击
	CreatedAt  int64  `json:"createdAt"`  //  创建时间
	Detail     string `json:"detail"`     // detail
}

type ArtListResp struct {
	Total int64           `json:"total"`
	List  []ArtDetailResp `json:"list"`
}

type Cat struct {
	Id        int64  `json:"id"`        //  id
	CreatedAt int64  `json:"createdAt"` //  创建时间
	Type      int    `json:"type"`      //栏目类型
	Title     string `json:"title"`     //标题
	Desc      string `json:"desc"`      //摘要
	TagList   string `json:"tagList"`   //标签列表
	Image     string `json:"image"`     //插图
	BeNav     bool   `json:"beNav"`     //是否导航
	Sort      int    `json:"sort"`      //排序
}

type CatListResp struct {
	Total int64 `json:"total"`
	List  []Cat `json:"list"`
}

type DiscussReq struct {
	Pid      int64  `json:"pid"`      //父ID
	ArtId    int64  `json:"artId"`    //id
	Title    string `json:"title"`    //标题
	Detail   string `json:"detail"`   //内容
	FileList string `json:"fileList"` //图片
}

type DiscussResp struct {
	Id        int64  `json:"id"`        //  id
	CreatedAt int64  `json:"createdAt"` //  创建时间
	Pid       int64  `json:"pid"`       //父ID
	ArtId     int64  `json:"artId"`     //id
	Title     string `json:"title"`     //标题
	Detail    string `json:"detail"`    //内容
	FileList  string `json:"fileList"`  //图片
}

type DiscussListResp struct {
	List []DiscussResp `json:"list"`
}

type PageInfoReq struct {
	Page     int    `json:"page"`     // 页码
	PageSize int    `json:"pageSize"` //页大小
	Key      string `json:"key"`      // key
}

type OkResp struct {
	Msg string `json:"msg"` //  返回msg
}

type IdReq struct {
	Id int64 `json:"id"` // id  请求
}

type ValReq struct {
	Val string `json:"val"` // 值 请求
}
