package business

import (
	plugin "go-cms/plugin/collect"
)

type ApiGroup struct {
	// Code generated by github.com/88act/go-cms/server Begin; DO NOT EDIT.
	ColHsjApi
	ColCollectApi2
	ColKeyFieldApi
	K8sPodsApi
	K8sNodesApi
	K8sNamespacesApi
	K8sDeploymentsApi
	K8sClustersApi
	ImTximApi
	ImTxMsgApi
	ImTxMsgFileApi
	CmsAdApi
	CmsArticleApi
	CmsCatApi
	BasicFileApi
	CmsAdSeatApi
	// Code generated by github.com/88act/go-cms/server End; DO NOT EDIT.
}

var collectManager = plugin.GetCollectManager()
