package business

import (
	plugin "go-cms/plugin/collect"
)

type ApiGroup struct {
	// Code generated by github.com/88act/go-cms/server Begin; DO NOT EDIT.
	ColHsjApi
	ColCollectApi2
	BasicFileApi
	ImTximApi2
	ColKeyFieldApi
	ColCollectApi
	CmsCatApi
	CmsArticleApi
	CmsAdApi
	CmsAdSeatApi
	ImTxFileApi
	ImTxMsgApi
	ImTxMsgFileApi
	ImTximApi
	K8sDeploymentsApi
	K8sClustersApi
	K8sNamespacesApi
	K8sNodesApi
	K8sPodsApi
	SysSuperBuilderHistoriesApi
	MemAddressApi
	BasicAreaApi
	MemUserLogApi
	MemUserSafeApi
	MemUserApi
	// Code generated by github.com/88act/go-cms/server End; DO NOT EDIT.
}

var collectManager = plugin.GetCollectManager()
