// Code generated by goctl. DO NOT EDIT!
// Source: act.proto

package act

import (
	"context"

	"go-cms/app/act/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ActDetailReq  = pb.ActDetailReq
	ActDetailResp = pb.ActDetailResp
	ActInfo       = pb.ActInfo
	ActListReq    = pb.ActListReq
	ActListResp   = pb.ActListResp

	Act interface {
		// actDetail
		ActDetail(ctx context.Context, in *ActDetailReq, opts ...grpc.CallOption) (*ActDetailResp, error)
		// actList
		ActList(ctx context.Context, in *ActListReq, opts ...grpc.CallOption) (*ActListResp, error)
	}

	defaultAct struct {
		cli zrpc.Client
	}
)

func NewAct(cli zrpc.Client) Act {
	return &defaultAct{
		cli: cli,
	}
}

// actDetail
func (m *defaultAct) ActDetail(ctx context.Context, in *ActDetailReq, opts ...grpc.CallOption) (*ActDetailResp, error) {
	client := pb.NewActClient(m.cli.Conn())
	return client.ActDetail(ctx, in, opts...)
}

// actList
func (m *defaultAct) ActList(ctx context.Context, in *ActListReq, opts ...grpc.CallOption) (*ActListResp, error) {
	client := pb.NewActClient(m.cli.Conn())
	return client.ActList(ctx, in, opts...)
}
