// Code generated by goctl. DO NOT EDIT.
package types

type FileInfo struct {
	Guid string `json:"guid"` //唯一id
	Path string `json:"path"` //文件路径
	Ext  string `json:"ext"`  //文件类型
	Size int    `json:"size"` //文件大小[k]
}

type FileListReq struct {
	Ids []string `json:"ids"`
}

type FileListResp struct {
	List []FileInfo `json:"list"`
}

type FileDetailReq struct {
	Id string `json:"id"`
}

type FileDetailResp struct {
	Info FileInfo `json:"info"`
}

type UploadReq struct {
}

type UploadResp struct {
	Info FileInfo `json:"info"`
}

type GetKeyReq struct {
}

type GetKeyResp struct {
	Key        string `json:"key"`
	ExpireTime int32  `json:"expireTime"`
}

type GetCaptchaReq struct {
	Key string `json:"key"`
}

type GetCaptchaResp struct {
	Image string `json:"image"`
}

type GetCodeReq struct {
	SendType   int32  `json:"sendType"`   // 1 短信 2 邮件
	Phone      string `json:"phone"`      // 1 短信 2 邮件
	VerilyType int32  `json:"verilyType"` //验证码类型 1注册,2密码登录,3手机登录,4修改密码
	Key        string `json:"key"`
	Code       string `json:"code"`
}

type GetCodeResp struct {
}
