// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	order "looklook/app/order/cmd/api/internal/handler/order"
	"looklook/app/order/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/order/addOrder",
				Handler: order.AddOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/orderList",
				Handler: order.OrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/orderDetail",
				Handler: order.OrderDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/updateOrder",
				Handler: order.UpdateOrderHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/order/v1"),
	)
}
