package business

type RouterGroup struct {
	// Code generated by github.com/88act/go-cms/server Begin; DO NOT EDIT.
	BusinessExampleRouter
	BasicFileRouter
	CmsAdSeatRouter
	CmsAdRouter
	CmsArticleRouter
	CmsCatRouter
	ColKeyFieldRouter
	ColHsjRouter
	ColCollectRouter
	// Code generated by github.com/88act/go-cms/server End; DO NOT EDIT.
}
