// Code generated by goctl. DO NOT EDIT!
// Source: act.proto

package server

import (
	"context"

	"go-cms/app/act/cmd/rpc/internal/logic"
	"go-cms/app/act/cmd/rpc/internal/svc"
	"go-cms/app/act/cmd/rpc/pb"
)

type ActServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedActServer
}

func NewActServer(svcCtx *svc.ServiceContext) *ActServer {
	return &ActServer{
		svcCtx: svcCtx,
	}
}

// actDetail
func (s *ActServer) ActDetail(ctx context.Context, in *pb.ActDetailReq) (*pb.ActDetailResp, error) {
	l := logic.NewActDetailLogic(ctx, s.svcCtx)
	return l.ActDetail(in)
}

// actList
func (s *ActServer) ActList(ctx context.Context, in *pb.ActListReq) (*pb.ActListResp, error) {
	l := logic.NewActListLogic(ctx, s.svcCtx)
	return l.ActList(in)
}
