package business

import (
	plugin "github.com/88act/go-cms/server/plugin/collect"
	"github.com/88act/go-cms/server/service"
)

type ApiGroup struct {
	// Code generated by github.com/88act/go-cms/server Begin; DO NOT EDIT.
	BusinessExampleApi
	BasicFileApi
	CmsAdSeatApi
	CmsAdApi
	CmsArticleApi
	CmsCatApi
	ColKeyFieldApi
	ColHsjApi
	ColCollectApi
	// Code generated by github.com/88act/go-cms/server End; DO NOT EDIT.
}

var commDbService = service.ServiceGroupApp.CommonServiceGroup.CommonDbService
var commFileService = service.ServiceGroupApp.CommonServiceGroup.CommonFileService

var collectManager = plugin.GetCollectManager()
