// Code generated by goctl. DO NOT EDIT.
package types

type MemUser struct {
	Id       int64  `json:"id"`       // 用户id
	Username string `json:"username"` //用户名
	Mobile   string `json:"mobile"`   //手机
	Nickname string `json:"nickname"` //昵称
	Realname string `json:"realname"` //真实名
	Sex      int    `json:"sex"`      //性别
	Avatar   string `json:"avatar"`   //头像
	Status   int    `json:"status"`   //状态
	CuId     int64  `json:"cuId"`     //客户id
	CuGuid   string `json:"cuGuid"`   //客户GUID
}

type LoginReq struct {
	Username string `json:"username"` //用户名
	Password string `json:"password"` //密码
}

type LoginScanReq struct {
	Value string `json:"value"` //  二维码值
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"` //认证token
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UserInfoResp struct {
	UserInfo MemUser `json:"userInfo"` //用户信息
}

type PageInfoReq struct {
	Page           int    `json:"page"`
	PageSize       int    `json:"pageSize"`
	Order          string `json:"order"`
	Desc           bool   `json:"desc"`
	SearchKey      string `json:"searchKey"`
	Status         int    `json:"status"`
	CreatedAtBegin string `json:"createdAtBegin"`
	CreatedAtEnd   string `json:"createdAtEnd"`
}

type IdReq struct {
	Id int64 `json:"id"` // id  请求
}

type ValReq struct {
	Value string `json:"value"` // 值 请求
}

type IdListReq struct {
	IdList []int64 `json:"idList"` // idList 请求
}

type GuidListReq struct {
	GuidList []string `json:"guidList"` // guidList 请求
}

type IdValueReq struct {
	Table string `json:"table"` //对应表
	Id    int64  `json:"id"`    // id
	Value string `json:"value"` //值
}

type IdValueListReq struct {
	IdValueList []IdValueReq `json:"idValueList"` // IdValueList
}

type OkResp struct {
	Msg string `json:"msg"`
}

type IdValue struct {
	Id    int64  `json:"id"`    // id
	Value string `json:"value"` //值
	Path  string `json:"path"`  //url
}

type IdValueListResp struct {
	List []IdValue `json:"list"`
}

type FileObj struct {
	Path string `json:"path"`
	Guid string `json:"guid"`
}
