 # github.com/88act/go-cms/server Global Configuration

# mysql connect configuration

mysql:

  path: 127.0.0.1:53306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: go-cms-builder
  username: root
  password: 123456

  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

# system configuration
system:
  go-mode: 'debug'  # go 是否 release/debug 模式  
  env: 'public'  # 是否权限检查 Change to "develop" to skip authentication for development mode
  addr: 40050 # 8888
  db-type: 'mysql'
  oss-type: 'local'    # 控制oss选择走本期还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 NewOss函数配置
  use-multipoint: false
  # IP限制次数 一个小时15000次
  iplimit-count: 15000
  #  IP限制一个小时
  iplimit-time: 3600


# jwt configuration
jwt:
  signing-key: 'go-cms'
  expires-time: 604800
  buffer-time: 86400

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[GoCms]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# redis configuration
redis:
  open: 0
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

# email configuration
email:
  to: 'xxx@qq.com'
  port: 465
  from: 'xxx@163.com'
  host: 'smtp.163.com'
  is-ssl: true
  secret: 'xxx'
  nickname: 'test'

# casbin configuration
casbin:
  model-path: './resource/rbac_model.conf'

# captcha configuration
captcha:
  key-long: 2
  img-width: 240
  img-height: 80


# local configuration
local:
  base-url: http://localhost:40050/
  base-path: C:/work_go/go-cms-builder/server/
  path: res/sys
  path-user: res/user

# super-builder configuration
super-builder:
  transfer-restart: true
  # root 自动适配项目根目录
  # 请不要手动配置,他会在项目加载的时候识别出根路径
  root: ""
  server: /server
  server-api: /api/v1/business
  server-initialize: /initialize
  server-model: /model/business
  server-request: /model/business/request/
  server-router: /router/business
  server-service: /service/business
  web: /web/src
  web-api: /api
  web-form: /view
  web-table: /view

# qiniu configuration (请自行七牛申请对应的 公钥 私钥 bucket 和 域名地址)
qiniu:
  zone: 'ZoneHuaDong'
  bucket: ''
  img-path: ''
  use-https: false
  access-key: ''
  secret-key: ''
  use-cdn-domains: false


# aliyun oss configuration
aliyun-oss:
  endpoint: 'yourEndpoint'
  access-key-id: 'yourAccessKeyId'
  access-key-secret: 'yourAccessKeySecret'
  bucket-name: 'yourBucketName'
  bucket-url: 'yourBucketUrl'
  base-path: 'yourBasePath'

# tencent cos configuration
tencent-cos:
  bucket: 'xxxxx-10005608'
  region: 'ap-shanghai'
  secret-id: 'xxxxxxxx'
  secret-key: 'xxxxxxxx'
  base-url: 'https://gin.vue.admin'
  base-path: 'yourBasePath'
  path-prefix: 'github.com/88act/go-cms/server'

# excel configuration
excel:
  dir: './resource/excel/'


# timer task db clear table
Timer:
  start: true
  spec: "@daily"  # 定时任务详细配置参考 https://pkg.go.dev/github.com/robfig/cron/v3
  detail: [
    # tableName: 需要清理的表名
    # compareField: 需要比较时间的字段
    # interval: 时间间隔, 具体配置详看 time.ParseDuration() 中字符串表示 且不能为负数
    # 2160h = 24 * 30 * 3 -> 三个月
    { tableName: "sys_operation_records" , compareField: "created_at", interval: "2160h" },
    { tableName: "jwt_blacklists" , compareField: "created_at", interval: "168h" }
    #{ tableName: "log2" , compareField: "created_at", interval: "2160h" }
  ]
