#服务器许可证
license:  
  rsaPath: D:/work_go/go-cms_server/server # 公钥路径
  appId: 20fc1872ddbf40e38fa1a59a99c1191b            # 产品ID go-cms服务器端
  maxClient: 20        # 客户端数量 
  endTime: 4822854526   # 到期时间
  rtcType: 1           # 远程模式  0 关闭  1 开启
  license: oMAKfP/YmTtoQUZWmIKHlaqebXYMC92cu5zgKfKrpBSBbLeWsQV6AJBb+K5v/tpRaCcAhhloVPd0XbC7vPCpkL4aGZS/FPFfGC1QF0MjXj+TxDGwvWOBRLKJm3fiU34KIFmuNYe0xOBVlBmn8kD91XeW2j7w84PvW5TWWjJ6tW9kSFifuXbEDSsVvN4R/0rORcrAWT0F7Y+9dzklKLWHnOqAOayJU+JQ/KRaqB+bt+k8zbNnDUZ7dXR/GH1Nl00axH13iZ90gyE6/eWSrTAplarqeDEoVhqCJ/NEPcT8b2wtNXM9WFoPGbIPnnyuQc5pwJOJ+1UDd/DUSvTeslKCjA==

mysql: 
  path: mysql-gocms:53306 
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: go-cms
  username: gocms
  password: gocms123456  
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false
  
# redis configuration
redis:
  open: 1
  db: 2
  addr: 'redis:6379'
  #addr: '192.168.1.18:6379'
  #password: 'G62m50oigInC30sf'

# system configuration
system:
  superAdmin: false  #  超管理模式，全菜单和全权限 
  go-mode: 'release'  # go 是否 release/debug 模式  
  env: 'develop'  # 是否权限检查 Change to "develop" to skip authentication for development mode
  addr: 44088 # 8888
  db-type: 'mysql'
  oss-type: 'local'    # 控制oss选择走本期还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 NewOss函数配置
  use-multipoint: false
  # IP限制次数 一个小时15000次
  iplimit-count: 15000
  #  IP限制一个小时
  iplimit-time: 3600
  rsa-path: D:/work_go/go-cms/server/
  api-url: https://www.go-cms.com/
  # wss-url: wss://www.go-cms.com/wss/  
  #wss-url: ws://127.0.0.1:8888/   
  wss-url: wss://10.0.0.222/wss/  

# jwt configuration
jwt:  
  signing-key: 'go-cms'
  expires-time: 604800
  buffer-time: 86400

# local configuration
local:
  base-url: http://127.0.0.1:44088/
  base-path: D:/work_go/go-cms/server/
  path: res/sys
  path-user: res/user  

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[te]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true


# email configuration
email:
  to: 'xxx@qq.com'
  port: 465
  from: 'xxx@163.com'
  host: 'smtp.163.com'
  is-ssl: true
  secret: 'xxx'
  nickname: 'test'

# casbin configuration
casbin:
  model-path: './resource/rbac_model.conf'

# captcha configuration
captcha:
  key-long: 2
  img-width: 240
  img-height: 80 
 
# qiniu configuration (请自行七牛申请对应的 公钥 私钥 bucket 和 域名地址)
qiniu:
  zone: 'ZoneHuaDong'
  bucket: ''
  img-path: ''
  use-https: false
  access-key: ''
  secret-key: ''
  use-cdn-domains: false


# aliyun oss configuration
aliyun-oss:
  endpoint: 'yourEndpoint'
  access-key-id: 'yourAccessKeyId'
  access-key-secret: 'yourAccessKeySecret'
  bucket-name: 'yourBucketName'
  bucket-url: 'yourBucketUrl'
  base-path: 'yourBasePath'

# tencent cos configuration
tencent-cos:
  bucket: 'xxxxx-10005608'
  region: 'ap-shanghai'
  secret-id: 'xxxxxxxx'
  secret-key: 'xxxxxxxx'
  base-url: 'https://www.go-cms.com/'
  base-path: 'yourBasePath'
  path-prefix: 'poetsclub.jiquxr.com'

# excel configuration
excel:
  dir: './resource/excel/'
 