package business

type RouterGroup struct {
	// Code generated by github.com/88act/go-cms/server Begin; DO NOT EDIT.
	ColHsjRouter
	ColCollectRouter
	ColKeyFieldRouter
	K8sPodsRouter
	K8sNodesRouter
	K8sNamespacesRouter
	K8sDeploymentsRouter
	K8sClustersRouter
	ImTximRouter
	ImTxMsgRouter
	ImTxMsgFileRouter
	CmsAdRouter
	CmsArticleRouter
	CmsCatRouter
	BasicFileRouter
	CmsAdSeatRouter
	// Code generated by github.com/88act/go-cms/server End; DO NOT EDIT.
}
