package business

type RouterGroup struct {
	// Code generated by github.com/88act/go-cms/server Begin; DO NOT EDIT.
	ColHsjRouter
	BasicFileRouter
	ColKeyFieldRouter
	ColCollectRouter
	CmsCatRouter
	CmsArticleRouter
	CmsAdRouter
	CmsAdSeatRouter
	ImTxFileRouter
	ImTxMsgRouter
	ImTxMsgFileRouter
	ImTximRouter
	K8sDeploymentsRouter
	K8sClustersRouter
	K8sNamespacesRouter
	K8sNodesRouter
	K8sPodsRouter
	MemAddressRouter
	BasicAreaRouter
	MemUserLogRouter
	MemUserSafeRouter
	MemUserRouter
	BbPiContactsRouter
	BbPiDepartmentRouter
	BbPiDeviceRouter
	BbPiInstitutionRouter
	BbPiInstitutionBusinessRouter
	BbPiPersonRouter
	BbPiServicePointRouter
	BbPiStaffRouter
	BbPiTreatmentOrderRouter
	BbPiTreatmentReferralRouter
	BbPiUpFieldRouter
	BbPiTreatmentDiagnoseRouter
	BbPiTreatmentRecordRouter
	// Code generated by github.com/88act/go-cms/server End; DO NOT EDIT.
}
