// Code generated by goctl. DO NOT EDIT!
// Source: basic.proto

package server

import (
	"context"

	"go-cms/app/basic/cmd/rpc/internal/logic"
	"go-cms/app/basic/cmd/rpc/internal/svc"
	"go-cms/app/basic/cmd/rpc/pb"
)

type BasicServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedBasicServer
}

func NewBasicServer(svcCtx *svc.ServiceContext) *BasicServer {
	return &BasicServer{
		svcCtx: svcCtx,
	}
}

// FileDetail //文件详情
func (s *BasicServer) FileDetail(ctx context.Context, in *pb.FileDetailReq) (*pb.FileDetailResp, error) {
	l := logic.NewFileDetailLogic(ctx, s.svcCtx)
	return l.FileDetail(in)
}

// FileList 文件列表
func (s *BasicServer) FileList(ctx context.Context, in *pb.FileListReq) (*pb.FileListResp, error) {
	l := logic.NewFileListLogic(ctx, s.svcCtx)
	return l.FileList(in)
}

// addFile 新增文件
func (s *BasicServer) AddFile(ctx context.Context, in *pb.AddFileReq) (*pb.AddFileResp, error) {
	l := logic.NewAddFileLogic(ctx, s.svcCtx)
	return l.AddFile(in)
}
