DROP TABLE IF EXISTS `act_act`;
CREATE TABLE `act_act` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '活动id',
  `user_id` bigint(20) unsigned NOT NULL COMMENT '用户id',
  `cat_id` int(10) NOT NULL DEFAULT '0' COMMENT '系统栏目',
  `cat_id_user` int(10) DEFAULT '0' COMMENT '用户栏目',
  `be_online` tinyint(1) DEFAULT '0' COMMENT '类型:0=线下 1=线上',
  `act_type` varchar(500) DEFAULT '' COMMENT '活动类型:1室内活动,2户外活动,3视频直播,4视频点播,5群组聊天,6文本文档',
  `be_multi` tinyint(1) DEFAULT '0' COMMENT '分期活动:0=否 1=是',
  `phase` int(10)  DEFAULT '0' COMMENT '分期',
  `title` varchar(150) DEFAULT NULL COMMENT '标题',
  `desc` varchar(500) DEFAULT NULL COMMENT '简介',
  `avater` varchar(100) DEFAULT '0' COMMENT '缩略图',
  `media_list` varchar(500) DEFAULT '' COMMENT '媒体列表',
  `address` varchar(500) DEFAULT NULL COMMENT '地址',
  `area_id` int(10) DEFAULT '0' COMMENT '地区id',
  `lng` bigint(20) unsigned DEFAULT '0' COMMENT '经度:无6位小数',
  `lat` bigint(20) unsigned DEFAULT '0' COMMENT '纬度:无6位小数',
  `begin_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `live_time` datetime DEFAULT NULL  COMMENT '直播开始',
  `live_end` datetime DEFAULT NULL COMMENT '直播结束',
  `presenter` varchar(200) DEFAULT "" COMMENT '主持/讲师',
  `phone_kefu` varchar(100) DEFAULT"" COMMENT '客服电话',
  `phone_hezu` varchar(100) DEFAULT "" COMMENT '合作电话',
  `wx` varchar(100) DEFAULT "" COMMENT '微信',
  `qq` varchar(100) DEFAULT "" COMMENT 'QQ',
  `group_id` varchar(100) DEFAULT "" COMMENT '群组id',
  `end_join_time` datetime DEFAULT NULL COMMENT '结束报名',
  `price` int(10) DEFAULT '0' COMMENT ' 票价:单位分',
  `price_vip` int(10) DEFAULT '0' COMMENT 'vip票价:单位分',
  `price_desc` varchar(200) DEFAULT "" COMMENT '票价描述', 
  `refund_type` smallint(2) DEFAULT '0' COMMENT '退费类型:1=不可退款 2=活动开始前都可退款 3=活动开始前n天可退费',
  `refund_days` smallint(2) DEFAULT '0' COMMENT '退费天:开始前n天退费',
  `be_showjoin` smallint(2) DEFAULT '0' COMMENT '是否显示人数:0=显示 1=不显示',
  `status_act` smallint(2) DEFAULT '0' COMMENT '活动状态:0未开始,1报名中,2停止报名,3进行中,4已结束,5评价期，6结束',
  `max_join` int(10) DEFAULT '0' COMMENT '最大报名人数',
  `now_join` int(10) DEFAULT '0' COMMENT '当前报名人数',
  `be_chosen` tinyint(1) DEFAULT '0' COMMENT '是否精选:0=否 1=是',
  `be_week` tinyint(1) DEFAULT '0' COMMENT '是否周末:0=否 1=是',
  `be_vip` tinyint(1) DEFAULT '0' COMMENT '是否会员:0=否 1=是',
  `total_whole` int(10) DEFAULT '0' COMMENT '综合指数', 
  `total_share` int(10) DEFAULT '0' COMMENT '总分享',
  `total_fav` int(10) DEFAULT '0' COMMENT '总收藏',
  `total_join` int(10) DEFAULT '0' COMMENT '总报名数',
  `total_discuss` int(10) DEFAULT '0' COMMENT '总评论',
  `total_click` int(10) DEFAULT '0' COMMENT '总点击',
  `total_star` int(10) DEFAULT '0' COMMENT '总评',
  `total_star_1` smallint(2) DEFAULT '0' COMMENT '总星评1:教学水平）',
  `total_star_2` smallint(2) DEFAULT '0' COMMENT '总星评2:课程质量）',
  `total_star_3` smallint(2) DEFAULT '0' COMMENT '总星评3:服务态度）', 
  `status` smallint(2) NOT NULL DEFAULT '0' COMMENT '状态:0未审核 1审核通过 2未通过审核 3草稿 ',
  `status_msg` varchar(500) DEFAULT "" COMMENT '审核原因', 
  `created_at` datetime DEFAULT NULL COMMENT '创建时间', 
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_cat_id` (`cat_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_total_click` (`total_click`),
  KEY `idx_total_discuss` (`total_discuss`),
  KEY `idx_total_join` (`total_join`),
  KEY `idx_be_online` (`be_online`),
  KEY `idx_be_multi` (`be_multi`),
  KEY `idx_be_chosen` (`be_chosen`),
  KEY `idx_be_vip` (`be_vip`),
  KEY `idx_price` (`price`), 
  KEY `idx_status_act` (`status_act`),
  KEY `idx_status` (`status`), 
  KEY `idx_total_whole` (`total_whole`) ,
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COMMENT='活动表';

DROP TABLE IF EXISTS `act_join`;
CREATE TABLE `act_join` (
  `id` int(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `act_id` bigint(20) unsigned NOT NULL COMMENT '活动id',
  `user_id` bigint(20) unsigned NOT NULL COMMENT '用户id', 
  `senior_id` bigint(20) unsigned NOT NULL COMMENT '分享人id', 
  `join_time` datetime DEFAULT NULL COMMENT '参加时间',
  `role` datetime DEFAULT NULL COMMENT '活动角色:0普通,1管理员',
  `remark`  varchar(500) DEFAULT "" COMMENT '备注', 
  `sing_code`  varchar(100) DEFAULT "" COMMENT '签到码', 
  `sing_time` datetime DEFAULT NULL COMMENT '签到时间', 
  `status` smallint(1)  DEFAULT '0' COMMENT '状态:0未审核 1审核通过 2未通过审核 3禁止报名',
  `status_msg` varchar(500) DEFAULT "" COMMENT '审核原因', 
  `created_at` datetime DEFAULT NULL COMMENT '创建时间', 
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_act_id` (`act_id`),
  KEY `idx_user_id` (`user_id`), 
  KEY `idx_status` (`status`),
  KEY `idx_deleted_at` (`deleted_at`) 
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COMMENT='活动报名表';
 
DROP TABLE IF EXISTS `act_select`;
CREATE TABLE `act_select` (
  `id` int(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `act_id` bigint(20) unsigned NOT NULL COMMENT '活动id',
  `user_id` bigint(20) unsigned NOT NULL COMMENT '用户id',  
  `select_list` varchar(500) DEFAULT "" COMMENT '选择用户', 
  `created_at` datetime DEFAULT NULL COMMENT '创建时间', 
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_act_id` (`act_id`),
  KEY `idx_user_id` (`user_id`) ,
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COMMENT='活动互选表';

DROP TABLE IF EXISTS `act_fav`;
CREATE TABLE `act_fav` (
  `id` int(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `user_id` bigint(20)  NOT NULL COMMENT '用户id',  
  `type` smallint(2)   DEFAULT '0' COMMENT '收藏类型:1活动,2文章',
  `obj_id` bigint(20)   DEFAULT '0' COMMENT '对象id', 
  `status` smallint(2)  DEFAULT '0' COMMENT '状态:0未审核 1审核通过 2未通过审核 3黑名单',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间', 
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_obj_id` (`obj_id`),
  KEY `idx_type` (`type`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_deleted_at` (`deleted_at`) 
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COMMENT='用户收藏表';

DROP TABLE IF EXISTS `act_fans`;
CREATE TABLE `act_fans` (
  `id` int(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `type` smallint(2) unsigned DEFAULT '0' COMMENT '粉丝分类:1店铺,2用户',
  `obj_id` bigint(20) unsigned NOT NULL COMMENT '店铺/用户id',   
  `fans_id` bigint(20) unsigned NOT NULL COMMENT '粉丝usrid', 
  `status` smallint(2) NOT NULL DEFAULT '0' COMMENT '状态:0未审核 1审核通过 2未通过审核 3黑名单',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间', 
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_obj_id` (`obj_id`),
  KEY `idx_type` (`type`),
  KEY `idx_fans_id` (`fans_id`),
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COMMENT='店铺/用户粉丝表';

 
DROP TABLE IF EXISTS `act_shop`;
CREATE TABLE `act_shop` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `user_id` bigint(20)  NOT NULL COMMENT '用户id',   
  `name` varchar(150) DEFAULT "" COMMENT '标题',
  `desc` varchar(500) DEFAULT "" COMMENT '简介', 
  `detail` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '详细内容',
  `avater` varchar(100) DEFAULT '' COMMENT '缩略图',
  `media_list` varchar(500) DEFAULT '' COMMENT '媒体列表',
  `address` varchar(500) DEFAULT "" COMMENT '地址',
  `area_id` int(10) DEFAULT '0' COMMENT '地区id',
  `lng` bigint(20) unsigned DEFAULT '0' COMMENT '经度:无6位小数',
  `lat` bigint(20) unsigned DEFAULT '0' COMMENT '纬度:无6位小数',
  `email` varchar(60) DEFAULT '' COMMENT '邮件',
  `mobile` varchar(20) DEFAULT '' COMMENT '手机', 
  `vip_lev` int(10) DEFAULT '0' COMMENT 'vip等级:0,1,2,3',
  `vip_time` datetime DEFAULT NULL COMMENT 'vip结束时间',
  `total_whole` int(10) DEFAULT '0' COMMENT '综合指数', 
  `total_share` int(10) DEFAULT '0' COMMENT '总分享',
  `total_fav` int(10) DEFAULT '0' COMMENT '总收藏',
  `total_join` int(10) DEFAULT '0' COMMENT '总报名人数',
  `total_discuss` int(10) DEFAULT '0' COMMENT '总评论',
  `total_click` int(10) DEFAULT '0' COMMENT '总点击',
  `total_star` int(10) DEFAULT '0' COMMENT '总评',
  `status` smallint(2) NOT NULL DEFAULT '0' COMMENT '状态:0未审核 1审核通过 2未通过审核 3黑名单',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间', 
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_vip_lev` (`vip_lev`),
  KEY `idx_deleted_at` (`deleted_at`),
  KEY `idx_total_whole` (`total_whole`) 
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COMMENT='店铺表';
 

  DROP TABLE
IF EXISTS `act_user`;

CREATE TABLE `act_user` (
	`user_id` BIGINT (20) NOT NULL COMMENT '用户id',
	`vip_lev` INT (10) DEFAULT '0' COMMENT 'vip等级:0,1,2,3',
	`vip_time` datetime DEFAULT NULL COMMENT 'vip时间',
	`realname` VARCHAR (100) DEFAULT "" COMMENT '姓名',
	`nickname` VARCHAR (100) DEFAULT "" COMMENT '昵称',
	`height` VARCHAR (100) DEFAULT "" COMMENT '身高[cm]',
	`weight` VARCHAR (100) DEFAULT "" COMMENT '体重[kg]',
	`age` VARCHAR (100) DEFAULT "" COMMENT '出生年月',
	`zodiac` VARCHAR (100) DEFAULT "" COMMENT '生肖',
	`star` VARCHAR (100) DEFAULT "" COMMENT '星座',
	`mobile` VARCHAR (100) DEFAULT "" COMMENT '手机',
	`weixin` VARCHAR (100) DEFAULT "" COMMENT '微信',
	`child` VARCHAR (100) DEFAULT "" COMMENT '小孩',
	`marriage` VARCHAR (100) DEFAULT "" COMMENT '婚否',
	`edu` VARCHAR (100) DEFAULT "" COMMENT '学历',
	`school` VARCHAR (100) DEFAULT "" COMMENT '毕业学校',
	`job` VARCHAR (100) DEFAULT "" COMMENT '职业',
	`income` VARCHAR (100) DEFAULT "" COMMENT '收入',
	`house` VARCHAR (200) DEFAULT "" COMMENT '房车情况',
	`city` VARCHAR (200) DEFAULT "" COMMENT '籍贯',
	`city_work` VARCHAR (200) DEFAULT "" COMMENT '工作城市',
	`desc` VARCHAR (100) DEFAULT "" COMMENT '自我评价',
	`z_age` VARCHAR (200) DEFAULT "" COMMENT '年龄要求',
	`z_height` VARCHAR (200) DEFAULT "" COMMENT '身高[cm]',
	`z_weight` VARCHAR (200) DEFAULT "" COMMENT '体重[kg]', 
	`z_child` VARCHAR (200) DEFAULT "" COMMENT '小孩',
	`z_marriage` VARCHAR (200) DEFAULT "" COMMENT '婚否',
	`z_edu` VARCHAR (200) DEFAULT "" COMMENT '学历',
	`z_income` VARCHAR (200) DEFAULT "" COMMENT '收入',
	`z_house` VARCHAR (200) DEFAULT "" COMMENT '房车情况',
	`z_city` VARCHAR (200) DEFAULT "" COMMENT '籍贯',
	`avater` VARCHAR (500) DEFAULT "" COMMENT '头像',
	`img_list` VARCHAR (500) DEFAULT "" COMMENT '图片列表',
	`be_open` TINYINT (1) DEFAULT '0' COMMENT '是否关闭:1=公开,0=关闭',
	`be_sharp` TINYINT (1) DEFAULT '0' COMMENT '是否分享:1=公开,0=否',
	`be_anonymous` TINYINT (1) DEFAULT '0' COMMENT '是否匿名:1=公开,0=匿名',
	`be_img` TINYINT (1) DEFAULT '0' COMMENT '审核图片:1=正常,0=关闭',
	`status` SMALLINT (2) NOT NULL DEFAULT '0' COMMENT '状态:0未审核 1审核通过 2未通过审核 3黑名单',
	`created_at` datetime DEFAULT NULL COMMENT '创建时间',
	`updated_at` datetime DEFAULT NULL,
	`deleted_at` datetime DEFAULT NULL,
	PRIMARY KEY (`user_id`), 
	KEY `idx_vip_lev` (`vip_lev`),
	KEY `idx_deleted_at` (`deleted_at`),
	KEY `idx_status` (`status`)
) ENGINE = INNODB AUTO_INCREMENT = 0 DEFAULT CHARSET = utf8mb4 COMMENT = '会员资料';


DROP TABLE IF EXISTS `order_order`;
CREATE TABLE `order_order` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '订单id',
  `sn` char(25)  NOT NULL DEFAULT '' COMMENT '订单号', 
  `user_id` bigint NOT NULL DEFAULT '0' COMMENT '用户id', 
  `order_type`  smallint(2) NOT NULL DEFAULT '0'  COMMENT '订单类型:1活动,2实物商品,3企业vip3,4个人vip,5抽奖红包',  
  `obj_id` bigint NOT NULL DEFAULT '0' COMMENT '对象id',   
  `price` int(10) DEFAULT '0' COMMENT '实付价',
  `price_src` int(10) DEFAULT '0' COMMENT '原价',
  `coupon_id` int(10) DEFAULT '0' COMMENT '优惠券ID', 
  `remark` varchar(500) DEFAULT "" COMMENT '备注',   
  `order_code` char(8)  NOT NULL DEFAULT '' COMMENT '核销码',  
  `state_order` smallint(2) NOT NULL DEFAULT '0' COMMENT '支付状态:-1已取消 0待支付 1未使用 2已使用 3已退款 4已过期',
  `status` smallint(2) NOT NULL DEFAULT '0' COMMENT '状态:0未审核 1审核通过 2未通过审核 3黑名单',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间', 
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_sn` (`sn`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_state_order` (`state_order`),
  KEY `idx_status` (`status`),
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB AUTO_INCREMENT = 0 DEFAULT CHARSET = utf8mb4 COMMENT='订单表';


DROP TABLE IF EXISTS `pay_payment`;
CREATE TABLE `pay_payment` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '支付id',
  `sn` char(25)  NOT NULL DEFAULT '' COMMENT '订单号',  
  `user_id` bigint NOT NULL DEFAULT '0' COMMENT '用户id',
  `pay_mode` varchar(20)  NOT NULL DEFAULT '' COMMENT '支付方式:1微信2支付宝3网银',
  `trade_type` varchar(20)   DEFAULT '' COMMENT '三方支付类型',
  `trade_state` varchar(20)  DEFAULT '' COMMENT '三方交易状态',
  `price` int(10) NOT NULL DEFAULT '0' COMMENT '总金额',
  `transaction_id` char(32) DEFAULT '0'  COMMENT '三方支付单号',
  `trade_state_desc` varchar(256)   DEFAULT '' COMMENT '支付状态',
  `order_sn` char(25)  DEFAULT '' COMMENT '业务单号',
  `service_type` varchar(32)  COMMENT '业务类型 ', 
  `status_pay` smallint(2)  NOT NULL DEFAULT '0' COMMENT '支付状态:-1:支付失败 0:未支付 1:支付成功 2:已退款',
  `pay_time` datetime NOT NULL  COMMENT '支付时间',
  `status` smallint(2) NOT NULL DEFAULT '0' COMMENT '状态:0未审核 1审核通过 2未通过审核 3黑名单',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间', 
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_sn` (`sn`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_status_pay` (`status_pay`),
  KEY `idx_status` (`status`),
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB AUTO_INCREMENT = 0 DEFAULT CHARSET = utf8mb4 COMMENT='第三方支付记录';



CREATE TABLE `pay_payment` (
  `id` bigint NOT NULL AUTO_INCREMENT  COMMENT '支付id',
  `sn` char(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '流水单号',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '版本号',
  `user_id` bigint NOT NULL DEFAULT '0' COMMENT '用户id',
  `pay_mode` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '支付方式:1微信2支付宝3网银',
  `trade_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '支付类型',
  `trade_state` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '交易状态',
  `pay_total` int NOT NULL DEFAULT '0' COMMENT '支付金额(分)',
  `transaction_id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '第三方支付单号',
  `trade_state_desc` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '支付状态描述',
  `order_sn` char(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '业务单号',
  `service_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '业务类型 ',
  `pay_status` smallint(2) NOT NULL DEFAULT '0' COMMENT '平台交易状态:-1:支付失败 0:未支付 1:支付成功 2:已退款',
  `pay_time` datetime NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '支付时间',
  `status` smallint(2) NOT NULL DEFAULT '0' COMMENT '状态:0未审核 1审核通过 2未通过审核 3黑名单',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间', 
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_sn` (`sn`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_pay_status` (`pay_status`),
  KEY `idx_status` (`status`),
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='支付流水记录';


