// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"github.com/zeromicro/go-zero/rest"
	act "go-cms/app/act/cmd/api/internal/handler/act"
	"go-cms/app/act/cmd/api/internal/svc"
	"net/http"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/act/actList",
				Handler: act.ActListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/act/actDetail",
				Handler: act.ActDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/act/shopList",
				Handler: act.ShopListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/act/shopDetail",
				Handler: act.ShopDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/act/v1"),
	)
}
