package business

type ServiceGroup struct {
	// Code generated by github.com/88act/go-cms/server Begin; DO NOT EDIT.

	ColHsjService
	K8sPodsService
	K8sNodesService
	K8sNamespacesService
	K8sDeploymentsService
	K8sClustersService
	CmsAdService
	CmsArticleService
	CmsCatService
	BasicFileService
	CmsAdSeatService
	MemUserService
	MemUserSafeService
	ColKeyFieldService
	ColCollectService
	ImTxFileService
	ImTximService
	ImTxMsgService
	ImTxMsgFileService
	// Code generated by github.com/88act/go-cms/server End; DO NOT EDIT.
}
