package business

type ServiceGroup struct {
	// Code generated by github.com/88act/go-cms/server Begin; DO NOT EDIT.

	ColHsjService
	BasicFileService
	ColKeyFieldService
	ColCollectService
	CmsCatService
	CmsArticleService
	CmsAdService
	CmsAdSeatService
	ImTxFileService
	ImTxMsgService
	ImTxMsgFileService
	ImTximService
	K8sDeploymentsService
	K8sClustersService
	K8sNamespacesService
	K8sNodesService
	K8sPodsService
	MemUserService
	MemUserSafeService
	// Code generated by github.com/88act/go-cms/server End; DO NOT EDIT.
}
