package business

type ServiceGroup struct {
	// Code generated by github.com/88act/go-cms/server Begin; DO NOT EDIT.

	ColHsjService
	ColCollectService
	ColKeyFieldService
	K8sPodsService
	K8sNodesService
	K8sNamespacesService
	K8sDeploymentsService
	K8sClustersService
	ImTximService
	ImTxMsgService
	ImTxMsgFileService
	CmsAdService
	CmsArticleService
	CmsCatService
	BasicFileService
	CmsAdSeatService
	// Code generated by github.com/88act/go-cms/server End; DO NOT EDIT.
}
