package common

//通用api 列表
type ApiGroup struct {
	// Code generated by github.com/88act/go-cms/server Begin; DO NOT EDIT.
	CommonDbApi
	CommonFileApi
	// Code generated by github.com/88act/go-cms/server End; DO NOT EDIT.
}
