package business

import "github.com/88act/go-cms/server/service/common"

type ServiceGroup struct {
	// Code generated by github.com/88act/go-cms/server Begin; DO NOT EDIT.
	BusinessExampleService
	CmsCatArtService
	BasicFileService
	CmsAdSeatService
	CmsAdService
	CmsArticleService
	CmsCatService
	ColKeyFieldService
	ColHsjService
	ColCollectService
	// Code generated by github.com/88act/go-cms/server End; DO NOT EDIT.
}

var commFileService = new(common.CommonFileService)
