// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	basic "go-cms/app/basic/cmd/api/internal/handler/basic"
	"go-cms/app/basic/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/basic/getKey",
				Handler: basic.GetKeyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/basic/getCaptcha",
				Handler: basic.GetCaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/basic/sendCode",
				Handler: basic.GetCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/basic/fileList",
				Handler: basic.FileListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/basic/fileDetail",
				Handler: basic.FileDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/basic/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/basic/upload",
				Handler: basic.UploadHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/basic/v1"),
	)
}
