// Code generated by goctl. DO NOT EDIT.
package types

type OrderInfo struct {
	Id          int64  `json:"id"`          //  id
	Sn          string `json:"sn"`          //订单号
	UserId      int64  `json:"userId"`      //用户id
	OrderType   int    `json:"orderType"`   //订单类型
	ObjId       int64  `json:"objId"`       //对象id
	Price       int    `json:"price"`       //实付价
	PriceSrc    int    `json:"priceSrc"`    //原价
	CouponId    int    `json:"couponId"`    //优惠券ID
	Title       string `json:"title"`       //标题
	Remark      string `json:"remark"`      //备注
	OrderCode   string `json:"orderCode"`   //核销码
	StatusPay   int    `json:"statusPay"`   //支付状态
	StatusOrder int    `json:"statusOrder"` //订单状态
	Status      int    `json:"status"`      //记录状态
}

type AddOrderReq struct {
	OrderType int    `json:"orderType"` //订单类型
	ObjId     int64  `json:"objId"`     //对象id
	Price     int    `json:"price"`     //实付价
	PriceSrc  int    `json:"priceSrc"`  //原价
	CouponId  int    `json:"couponId"`  //优惠券ID
	Title     string `json:"title"`     //标题
	Remark    string `json:"remark"`    //备注
}

type AddOrderResp struct {
	Sn string `json:"sn"` //订单号
}

type OrderDetailReq struct {
	Sn string `json:"sn"` //订单号
}

type OrderDetailResp struct {
	Info OrderInfo `json:"orderInfo"` //订单详情
}

type OrderListReq struct {
	Page     int32  `json:"page"`
	PageSize int32  `json:"pageSize"`
	Search   string `json:"search"`
}

type OrderListResp struct {
	List []OrderInfo `json:"list"` //订单详情
}

type UpdateOrderReq struct {
	Sn          string `json:"sn"`          //订单号
	CouponId    int    `json:"couponId"`    //优惠券ID
	Remark      string `json:"remark"`      //备注
	OrderCode   string `json:"orderCode"`   //核销码
	StatusOrder int    `json:"statusOrder"` //订单状态
	Status      int    `json:"status"`      //记录状态
}

type UpdateOrderResp struct {
	Rows int64 `json:"rows"` //行数
}
